# Generated by Django 4.0.5 on 2022-07-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_comment_user_alter_comment_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='reply_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comment'),
        ),
    ]
