# Generated by Django 4.0.5 on 2022-07-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
            preserve_default=False,
        ),
    ]
