# Generated by Django 4.0.5 on 2022-07-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reply_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
    ]
