# Generated by Django 4.0.5 on 2022-07-27 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_reply_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
