# Generated by Django 4.0.5 on 2022-07-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comment_blog_alter_comment_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
