# Generated by Django 4.0.5 on 2022-07-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_percent',
            field=models.IntegerField(max_length=255),
        ),
    ]
