# Generated by Django 4.0.5 on 2022-07-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_product_sale_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_percent',
            field=models.IntegerField(),
        ),
    ]
