from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Category)
admin.site.register(Color)
admin.site.register(Product)
admin.site.register(Review)
admin.site.register(Info)
admin.site.register(Subject)
admin.site.register(Blog)
admin.site.register(Comment)
admin.site.register(Reply)
admin.site.register(Cookies)
admin.site.register(Privacy_Policy)
admin.site.register(About)
admin.site.register(Requirements)
admin.site.register(Top_Trends)
admin.site.register(Delivery_Options)
admin.site.register(Order)
admin.site.register(OrderItem)
admin.site.register(Shipping_Detail)
admin.site.register(CartDetail)
admin.site.register(User)
admin.site.register(Wishlist)
admin.site.register(Contact)
admin.site.register(Rating)